// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Models.Goods.GoodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProducerId");

                    b.ToTable("GoodEntity");
                });

            modelBuilder.Entity("Models.Goods.GoodResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("Models.Races.RaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decadency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Needs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Will")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RaceEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af1c809d-407a-7b3c-0381-6196bbbf3212"),
                            CreatedAt = new DateTime(2022, 4, 24, 15, 45, 27, 903, DateTimeKind.Local).AddTicks(4354),
                            Decadency = "medium",
                            Description = "Est sed voluptatem voluptatem dolore.\nQui temporibus aliquid qui natus esse commodi veritatis.\nVoluptatibus amet inventore.\nVoluptas explicabo maiores aut vel.\nOptio sit pariatur possimus aspernatur architecto nulla.\nQuia id sequi et est sunt saepe eveniet.\nTemporibus hic ea.\nDicta ea velit possimus rerum quaerat dolore reprehenderit mollitia doloribus.\nIn eaque ut.\nVoluptas expedita accusantium.\nUt voluptatibus maxime illo voluptate qui molestias voluptatem et.\nFacilis tempora autem.",
                            Name = "quae",
                            Needs = "low",
                            Will = "low"
                        },
                        new
                        {
                            Id = new Guid("124c596c-6f5f-9af8-bec6-f9e99b5192b5"),
                            CreatedAt = new DateTime(2022, 3, 7, 7, 41, 36, 705, DateTimeKind.Local).AddTicks(8166),
                            Decadency = "medium",
                            Description = "Impedit libero necessitatibus architecto atque.\nNam et aut.\nQuia suscipit quas optio inventore dolores qui.\nFuga deleniti accusantium fugiat ex quia distinctio aut quo.\nQui ut laborum.\nUllam sapiente est quibusdam quis suscipit enim quisquam cum.\nVoluptatum cumque enim et ut aliquid sequi quae rerum.\nRepudiandae numquam dolores non labore molestiae perferendis voluptas.\nIpsa veniam voluptatem eum repellat sed eaque et sit.\nNemo ex voluptates quia esse.\nEst in nemo adipisci sapiente iure natus placeat sit.\nQui itaque sit sit sapiente exercitationem sit pariatur adipisci.",
                            Name = "minima",
                            Needs = "low",
                            Will = "high"
                        },
                        new
                        {
                            Id = new Guid("bb6f61cb-f8c8-375a-72f6-a9ca795427e0"),
                            CreatedAt = new DateTime(2022, 2, 28, 2, 18, 50, 811, DateTimeKind.Local).AddTicks(9763),
                            Decadency = "high",
                            Description = "Mollitia dicta rerum.\nAut consequatur repellendus excepturi commodi reprehenderit.\nSed quis a voluptatem dolore vitae fuga qui repellendus fuga.\nBlanditiis optio dolor unde.\nRem quos rerum voluptas laudantium praesentium ab et animi culpa.\nMinus sint rerum.\nDolor deserunt suscipit id excepturi quia fugiat esse.\nAut minus excepturi.\nNobis dolorem enim.\nFuga libero sint.\nAsperiores numquam vitae iste sunt ea neque aperiam voluptatem.\nVeritatis unde quisquam facere cupiditate minus.",
                            Name = "commodi",
                            Needs = "high",
                            UpdatedAt = new DateTime(2022, 12, 24, 18, 21, 10, 854, DateTimeKind.Local).AddTicks(3301),
                            Will = "medium"
                        },
                        new
                        {
                            Id = new Guid("36c2004a-b45c-f35d-1633-4781fb5a1e19"),
                            CreatedAt = new DateTime(2022, 3, 27, 1, 31, 16, 44, DateTimeKind.Local).AddTicks(4025),
                            Decadency = "high",
                            Description = "Tempora voluptates soluta aut nobis quia doloribus quo ipsum.\nAmet omnis voluptate temporibus est saepe.\nProvident sapiente voluptatem rerum consectetur error.\nDolores a quia excepturi repellendus odit.\nNisi a aut et quia nesciunt sed.\nNon voluptatem qui rerum error tenetur assumenda aut.\nId expedita nihil.\nDolore alias cum iure adipisci.\nDolor magni cumque harum corrupti consequatur aliquam asperiores.\nQuia hic qui excepturi quidem.\nAut quos ad quis.\nEst laudantium commodi.",
                            Name = "quas",
                            Needs = "medium",
                            Will = "low"
                        },
                        new
                        {
                            Id = new Guid("5be1f358-b704-027a-e237-fdb1947113b6"),
                            CreatedAt = new DateTime(2022, 9, 2, 6, 9, 37, 101, DateTimeKind.Local).AddTicks(2703),
                            Decadency = "low",
                            Description = "Est sequi accusantium delectus.\nMagnam quo eos voluptatem quia quo.\nNisi ut saepe provident sed nihil.\nDoloremque explicabo corrupti amet qui rem accusamus.\nEt voluptatibus asperiores sit adipisci corrupti non veritatis est.\nDebitis consequatur ipsam velit sequi.\nAutem aliquam sit id consequatur eaque provident.\nIpsa dolores enim iure nam id blanditiis ut sit.\nConsequatur tenetur ullam commodi.\nIn quibusdam nesciunt et nesciunt velit.\nOccaecati ducimus consectetur repudiandae consequatur iusto sint molestiae.\nVelit et illum cum aut veritatis recusandae qui nemo.",
                            Name = "cumque",
                            Needs = "high",
                            UpdatedAt = new DateTime(2023, 1, 14, 21, 21, 55, 736, DateTimeKind.Local).AddTicks(8560),
                            Will = "high"
                        },
                        new
                        {
                            Id = new Guid("034e6b64-897e-45b2-9aae-99b3667f2459"),
                            CreatedAt = new DateTime(2022, 7, 16, 7, 42, 14, 486, DateTimeKind.Local).AddTicks(6170),
                            Decadency = "high",
                            Description = "Quis ut qui at maiores optio aut eum.\nQuae sed iure et et sunt est.\nVoluptatem distinctio eum id.\nDoloremque ea id suscipit.\nPraesentium id dolore.\nQui molestias culpa iure voluptas.\nEarum et aut sunt suscipit laborum similique molestiae deleniti perspiciatis.\nVelit saepe voluptatem et voluptatum iure nisi quidem nemo ut.\nQui illo fugit quo occaecati consequatur autem cum aut illo.\nMagnam asperiores ut.\nQuia repellat mollitia aut sunt.\nRem ut ea.",
                            Name = "molestiae",
                            Needs = "medium",
                            UpdatedAt = new DateTime(2022, 10, 23, 6, 15, 42, 908, DateTimeKind.Local).AddTicks(7866),
                            Will = "high"
                        },
                        new
                        {
                            Id = new Guid("0e7f5f6e-78f1-a9a6-e671-31eb2bb50f61"),
                            CreatedAt = new DateTime(2022, 5, 16, 15, 50, 40, 834, DateTimeKind.Local).AddTicks(5789),
                            Decadency = "low",
                            Description = "Velit sunt perspiciatis eum ad.\nVitae ea qui magnam nemo distinctio aut dolores error.\nIllum quia enim sit id tenetur laudantium aut cumque consequatur.\nDolorum et sunt omnis.\nNam voluptatem accusamus pariatur quia molestiae modi mollitia a.\nBeatae inventore nemo est autem necessitatibus ut cumque.\nFacilis mollitia ipsam voluptate dignissimos.\nSit autem ea et repudiandae tempore culpa incidunt aperiam.\nOfficia cumque soluta consequatur consectetur impedit.\nVoluptates facilis mollitia rerum non eos.\nEt tempora in assumenda qui deserunt non nulla.\nSapiente sapiente a iure praesentium rerum.",
                            Name = "esse",
                            Needs = "low",
                            UpdatedAt = new DateTime(2022, 10, 14, 23, 53, 32, 260, DateTimeKind.Local).AddTicks(608),
                            Will = "medium"
                        },
                        new
                        {
                            Id = new Guid("2a8fbfc6-f292-fb81-2bf7-cc51c3ec86b0"),
                            CreatedAt = new DateTime(2022, 7, 18, 19, 42, 57, 401, DateTimeKind.Local).AddTicks(4917),
                            Decadency = "high",
                            Description = "Ut illum quia tenetur minus maiores.\nDelectus laboriosam est expedita.\nSuscipit autem ducimus qui quis nihil.\nSoluta sit esse eum et velit.\nVeniam aspernatur beatae.\nSunt nemo modi sunt atque et et.\nAutem quam et assumenda.\nA ut fugit delectus ut deserunt provident.\nSapiente vero enim qui.\nEsse suscipit necessitatibus et nemo molestias aut vel veritatis.\nIn corrupti debitis doloribus sunt dolorem aut ut odio ut.\nSapiente ut quia.",
                            Name = "quo",
                            Needs = "high",
                            UpdatedAt = new DateTime(2022, 2, 18, 7, 31, 43, 907, DateTimeKind.Local).AddTicks(8831),
                            Will = "medium"
                        });
                });

            modelBuilder.Entity("Models.Races.RaceResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decadency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Needs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Will")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Models.Goods.GoodEntity", b =>
                {
                    b.HasOne("Models.Races.RaceEntity", "Producer")
                        .WithMany("Products")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Models.Races.RaceEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
